# Generated by Django 5.2.6 on 2025-09-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.SmallIntegerField(choices=[(1, 'Terror'), (2, 'Romance'), (3, 'Policial'), (4, 'Jovem Adulto'), (5, 'Autoajuda')])),
                ('titulo', models.CharField(max_length=200)),
                ('ano', models.IntegerField()),
                ('autor', models.SmallIntegerField(choices=[(1, 'Jane Austen'), (2, 'Edgar Allan Poe'), (3, 'Aghata Christie'), (4, 'J. K. Rowling'), (5, 'Augusto Cury')])),
                ('editora', models.SmallIntegerField(choices=[(1, 'Darkside'), (2, 'Penguim Books'), (3, 'Martin Claret'), (4, 'Seguinte'), (5, 'Intrínseca')])),
            ],
        ),
    ]
