# Generated by Django 5.2.6 on 2025-10-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_livros'),
        ),
    ]
