# Generated by Django 5.2.6 on 2025-10-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_livro_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='livro/fotos/'),
        ),
    ]
