# Generated by Django 5.2.6 on 2025-11-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.SmallIntegerField(choices=[(1, 'Jane Austen'), (2, 'Edgar Allan Poe'), (3, 'Aghata Christie'), (4, 'J. K. Rowling'), (5, 'Augusto Cury'), (6, 'Machado de Assis'), (7, 'George Orwell'), (8, 'Stephen King'), (9, 'J. R. R. Tolkien'), (10, 'Clarice Lispector')]),
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.SmallIntegerField(choices=[(1, 'Darkside'), (2, 'Penguim Books'), (3, 'Martin Claret'), (4, 'Seguinte'), (5, 'Intrínseca'), (6, 'Companhia das Letras'), (7, 'Record'), (8, 'Rocco'), (9, 'Aleph'), (10, 'Cosac Naify')]),
        ),
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.SmallIntegerField(choices=[(1, 'Terror'), (2, 'Romance'), (3, 'Policial'), (4, 'Jovem Adulto'), (5, 'Autoajuda'), (6, 'Clássico'), (7, 'Distopia'), (8, 'Ficção Científica'), (9, 'Fantasia'), (10, 'Literatura Brasileira')]),
        ),
    ]
