# Generated by Django 5.2.6 on 2025-11-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0005_alter_livro_autor_alter_livro_editora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='sinopse',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Sinopse'),
        ),
    ]
