# Generated by Django 5.2.6 on 2025-11-27 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0006_livro_sinopse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(choices=[('avatar1.png', 'Clássico'), ('avatar2.png', 'Leitor'), ('avatar3.png', 'Óculos'), ('avatar4.png', 'Jovem')], default='avatar1.png', max_length=50)),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Sobre mim')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
